// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjfKKsyYGT4yHJcDozljGIjeYeIFGFeLY',
    appId: '1:90458386362:web:23509b102d487a34d87783',
    messagingSenderId: '90458386362',
    projectId: 'itsokbro-9bef7',
    authDomain: 'itsokbro-9bef7.firebaseapp.com',
    storageBucket: 'itsokbro-9bef7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJBLzdaux39fmg1Tlxo-p-mjRdeiOX1Q',
    appId: '1:90458386362:android:224c3092426c818ed87783',
    messagingSenderId: '90458386362',
    projectId: 'itsokbro-9bef7',
    storageBucket: 'itsokbro-9bef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsCHtDySW5xe4dpbpN8eZ9jOjnEzVDHMA',
    appId: '1:90458386362:ios:0579ca15060acfead87783',
    messagingSenderId: '90458386362',
    projectId: 'itsokbro-9bef7',
    storageBucket: 'itsokbro-9bef7.firebasestorage.app',
    iosBundleId: 'com.example.ownerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsCHtDySW5xe4dpbpN8eZ9jOjnEzVDHMA',
    appId: '1:90458386362:ios:0579ca15060acfead87783',
    messagingSenderId: '90458386362',
    projectId: 'itsokbro-9bef7',
    storageBucket: 'itsokbro-9bef7.firebasestorage.app',
    iosBundleId: 'com.example.ownerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjfKKsyYGT4yHJcDozljGIjeYeIFGFeLY',
    appId: '1:90458386362:web:398b4d0c05e57a37d87783',
    messagingSenderId: '90458386362',
    projectId: 'itsokbro-9bef7',
    authDomain: 'itsokbro-9bef7.firebaseapp.com',
    storageBucket: 'itsokbro-9bef7.firebasestorage.app',
  );

}